version: "3.9"

services:
  python:
    build:
      context: ./
      dockerfile: ./dockerfile
      args: 
        - GIT_USER_MAIL=$GIT_USER_MAIL
        - GIT_USER_NAME=$GIT_USER_NAME

    container_name: python
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - type: bind
        source: $PWD
        target: /app
    command: /bin/sh -c "while sleep 1000; do :; done"

